name: CI Master

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

jobs:
  "Test-with-SML-NJ":
    runs-on: ubuntu-latest
    container:
      image: floresbruno/sml-nj-ci:v0.0.4
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Test
        run: |
          cd driver/smlnj
          ml-build all.cm Driver.main all
          sml @SMLload=all

  "Test-with-MLton":
    runs-on: ubuntu-latest
    container:
      image: floresbruno/mlton-ci:v0.0.2
    strategy:
      matrix:
        backend: ["native", "amd64", "c", "llvm"]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Test
        run: |
          cd driver/mlton
          mlton -codegen ${{ matrix.backend }} -output all driver.mlb
          ./all
